export const ROUTES = {
  HOME: "/",
  BROWSE: "/browse",

  MOVIES: "/movies",
  MOVIE_DETAILS: "/movies/:movieId",
  MOVIES_GENRE: "/movies/genre/:genreId",
  MOVIES_TOPGENRE: "/movies/topGenre/:genreId",
  MOVIES_TRENDING: "/movies/trending",
  MOVIES_UPCOMING: "/movies/upcoming",
  MOVIES_POPULAR: "/movies/popular",
  MOVIES_FAVORITE: "/movies/favorite",
  MOVIES_WATCHLIST: "/movies/watchlist",

  TV: "/tv",
  TV_DETAILS: "/tvs/:tvId",
  TV_EPISODES: "/tvs/:tvId/:seasonId",
  TV_GENRE: "/tvs/genre/:genreId",
  TV_TOPGENRE: "/tvs/topGenre/:genreId",
  TV_TRENDING: "/tvs/trending",
  TV_UPCOMING: "/tvs/upcoming",
  TV_POPULAR: "/tvs/popular",
  TV_FAVORITE: "/tvs/favorite",
  TV_WATCHLIST: "/tvs/watchlist",

  SUPPORT: "/support",
  SUBSCRIPTIONS: "/subscriptions",
  SEARCH: "/search",
  AUTHENTICATION: "/authentication",
};
