export const plans = [
  {
    name: "Basic",
    price: "$9.99/Month",
    content:
      "Access to a wide selection of movies and shows, including some new releases.",
    devices: "Watch on one device simultaneously",
    trial: "7 Days",
    cancel: "Yes",
    hdr: "No",
    atmos: "No",
    adFree: "No",
    offline: "No",
    family: "No",
  },
  {
    name: "Standard",
    label: "Popular",
    price: "$12.99/Month",
    content:
      "Access to a wider selection of movies and shows, including most new releases and exclusive content",
    devices: "Watch on Two device simultaneously",
    trial: "7 Days",
    cancel: "Yes",
    hdr: "Yes",
    atmos: "Yes",
    adFree: "Yes",
    offline: "Yes, for select titles.",
    family: "Yes, up to 5 family members.",
  },
  {
    name: "Premium",
    price: "$14.99/Month",
    content:
      "Access to a widest selection of movies and shows, including all new releases and Offline Viewing",
    devices: "Watch on Four device simultaneously",
    trial: "7 Days",
    cancel: "Yes",
    hdr: "Yes",
    atmos: "Yes",
    adFree: "Yes",
    offline: "Yes, for all titles.",
    family: "Yes, up to 6 family members.",
  },
];
